### ISSUE TITLE
Annual?

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#2]
do we want to provide historic annual crime stats for these agencies? If so, do we scrape [these](http://www.njsp.org/info/stats.html#ucr) too or take it from the FBI?

**Comment by sstirling** [comment]
I think this a good idea.  It's good to have, and I know we haven't made any significant effort to grab all this recently at the Ledger.  I'd probably opt for taking the FBI data, though, since it's more manageable and likely has been finalized by the time it's published.

**Comment by CarlaAstudillo** [comment]
I agree with Steve on the FBI data. I think it also has numbers going back to 80's too.

**Comment by tommeagher** [comment]
We could offer two datasets: annual (up through 2012, for now), which would be considered canonical, and then monthly that can update with each revision until the annuals come out. 

For the annual data, the FBI is certainly in a much better format and easier to handle. The only problem is that it's nearly 18 months behind. @CarlaAstudillo, do you have a sense of how greatly the final FBI figures differ from the NJSP annual reports that come out in November?

Is the State Police even doing the annual reports any more, or is the December monthly report, with YTD figures, all they do?

**Comment by CarlaAstudillo** [comment]
Just a cursory glance between the FBI UCR 2012 data and the NJSP 2012 annual report for violent crimes for the state of New Jersey in 2012, I see differences between the two numbers. The murder and robbery are only 1 off, while the rape and aggravated assault numbers had some greater difference. For example, FBI had 12,919 while NJSP had 12,933 for aggravated assaults.

I don't see any NJSP annual reports for 2013 and 2014 in the site. So maybe they really did stop issuing them?

**Comment by sstirling** [comment]
Yeah I'm not really sure, Carla.  We can ask and see what's available.

On Tue, Mar 31, 2015 at 11:39 AM, CarlaAstudillo notifications@github.com
wrote:

> Just a cursory glance between the FBI UCR 2012 data and the NJSP 2012
> annual report for violent crimes for the state of New Jersey in 2012, I see
> differences between the two numbers. The murder and robbery are only 1 off,
> while the rape and aggravated assault numbers had some greater difference.
> For example, FBI had 12,919 while NJSP had 12,933.
> 
> I don't see any NJSP annual reports for 2013 and 2014 in the site. So
> maybe they really did stop issuing them?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackJersey/crime/issues/2#issuecomment-88137127.

## 

Stephen Stirling
Staff Writer
Computer Assisted Reporting Team
The Star-Ledger
Office: 973.392.4174
Cell: 908.720.5363

**Comment by tommeagher** [comment]
Do either of you have a good link for bulk download of this? It's going to be a pain to have to automate the custom table-maker on the FBI's website.

**Comment by sstirling** [comment]
I _think_ table 8 is what we're looking for.  

http://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2013/crime-in-the-u.s.-2013/tables/table-8/table-8-state-cuts/table_8_offenses_known_to_law_enforcement_new_jersey_by_city_2013.xls

Download link is at top.  Did you mean for all years?

**Comment by tommeagher** [comment]
Yup, from 1985-2012.

**Comment by tommeagher** [comment]
Actually, at a quick glance, there are 479 agencies in the FBI UCR. The State Police's reports have ~542. So some agencies will not have historic or annual data available. Not the end of the world, but worth considering.

**Comment by tommeagher** [comment]
Also just noticed that table doesn't include agency ORI ids or counties.
