### ISSUE TITLE
Geography of jurisdictions

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#23]
What would it take to create a geo shapefile of the jursidictions of all of [these agencies](https://github.com/HackJersey/crime/blob/master/lookup_agency.csv)?

**Comment by sstirling** [comment]
I don't know that I've ever seen a boundary file out there.  Carla, have
you?  That said, I've never looked too hard either.  I can poke around on
my GIS resources.

On Mon, May 4, 2015 at 1:34 PM, Tom Meagher notifications@github.com
wrote:

> What would it take to create a geo shapefile of the jursidictions of all
> of these agencies
> https://github.com/HackJersey/crime/blob/master/lookup_agency.csv?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackJersey/crime/issues/23.

## 

Stephen Stirling
Staff Writer
Computer Assisted Reporting Team
The Star-Ledger
Office: 973.392.4174
Cell: 908.720.5363
