### ISSUE TITLE
Make a functioning scraper

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#3]
First, let's get a program together to scrape and parse the monthly UCR PDFs.

**Comment by tommeagher** [comment]
This explanation of using the Tabula Ruby gem may be an approach to mimic: 
http://open.blogs.nytimes.com/2015/04/03/purifying-the-sea-of-pdf-data-automatically/

**Comment by sstirling** [comment]
How serendipitous.

**Comment by tommeagher** [comment]
OK. I have got this mostly working using a couple of command line tools, namely [docsplit](https://documentcloud.github.io/docsplit/) and [tabula-extractor](https://github.com/tabulapdf/tabula-extractor). Here's the pseudo-code version of what I've been testing.
- Burst the document into its individual pages with docsplit and then run tabula-extractor on every doc in the folder and output a new csv. 
  `docsplit pages 20150327_crimetrend.pdf`

For naming our csvs and for ultimately importing into a db, we need the date of publication and the time period the data covers. 
- We can grab the date of publication from the upper right corner of the doc, or the first line in the tabula output:
  `tabula -p 1 20150327_crimetrend.pdf | head -n 1 | cut -d , -f6-`
- We can grab the time period covered by this data from line 5:
  `tabula -p 1 20150327_crimetrend.pdf | sed -n '5p' | cut -d , -f6-`
- For each pdf in the directory, run it through tabula and just extract the unique ID:
  `tabula -p 1 20150327_crimetrend.pdf|grep -E '^N.+  Total'|cut -d , -f1|cut -d T -f 1`
  If agency id = "New Jersey", then convert that to "statewide"
- Name the file with the date YYYY-MM-DD-AGENCY-ID. For each page, pull the table and output it to a CSV file.
  `tabula -p 1 -a 97.55,11.19,573.48,778.62 -o YYYY-MM-DD-AGENCY-ID-.csv 20150327_crimetrend.pdf`
  We may also want to add the time period covered to the filename.
- Add the column heds:
  `crime, month_last_yr, month_this_yr, pct_chg, ytd_last, ytd_this_yr, ytd_pct_chg, cleared, pct_cleared, juvie_cleared`

In the resulting csv, remove any row with no values after the first column and any row that starts with "total".

Now I want to write this as a coherent Ruby script rather than a bunch of hacky command line tools piped to one another.
