### ISSUE TITLE
The state police is now using xls files!!!

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#34]
Have to rewrite scraper to handle these.

**Comment by tommeagher** [comment]
Also have to update our models to accept xls files in addition to csv

**Comment by tommeagher** [comment]
add excel files in s3 to the database

**Comment by SteadyGiant** [comment]
Are you currently actively working on this, @tommeagher? If not, I might take a crack at it soon. I don't know Ruby so it'd be slow going, but I could rewrite the thing in R or Python.

**Comment by tommeagher** [comment]
@everetr, hi! I have not started working on this yet, but if you'd like to take a crack at it, that'd be great. 
Since I've moved the website to the Django framework, it'd be better/easier to have these new scripts in Python. At some point I may port the scripts for converting the PDFs to csv from jRuby to Python as well. Some day.
Anyway, the goal here is to create a single CSV for each department for each release. Here's a sample from the old PDFs: https://dycbt2qke8skt.cloudfront.net/csv/2016-06-06-for-2018-05-NJ0010200-SAMPLE.csv
After we get the pipeline for all the releases converted to CSVs, we would then read all of them into a database that'll be accessible via API. 
Obviously the layout of these new Excel spreadsheets is different, but if we can get them into CSVs, I can figure out how to reconcile them all later when we create the database. Does this make sense?
