### ISSUE TITLE
What are we making?

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#4]
Obviously, we want to start by scraping and databasing the monthly reports (see #3), but then what do we want to do with it? 

What would you want as a journalist in NJ?

Do we provide an API, or downloadable CSVs, or an email notification service when it updates? Let's hash this out a bit before we get too deep into it. Once we decide what to build, we can talk about how to build it.

**Comment by CarlaAstudillo** [comment]
Hmm… good question. I always hear from local reporters that they wish they could quickly pick a bunch of towns and find the monthly crime data they need without going through the bulky PDF. So maybe we could display it in a way that gives them the town stats they need quickly (with the choice of also downloading it as a CSV too). Maybe even display it in such a way that they can compare between two towns for a story.

This might be getting too optimistic here, but maybe something like a much less-fancy version of Census Reporter, but for NJ UCR data.

**Comment by KevinStirling** [comment]
What is the preferred way to display this kind of information? Through a table? Or something more visual like a chart or graph?

**Comment by sstirling** [comment]
Going off of what Carla suggested, an ambitious take would be a mix of searchable, sortable data tables and more visually dynamic elements like charts and/or maps. I think making raw data available is a must. 

Regardless though, I think giving reporters a quick, painless way to access municipal and/or county level data is key.

**Comment by sstirling** [comment]
Also! I don't believe UCR has crime rate data in there (I may be mistaken) but generally does include population.  Presenting violent/non-violent crime rates, I think, would be pretty important because reporters often compare raw figures to each other, which leads to misconceptions.

**Comment by tommeagher** [comment]
These are all great ideas that seem doable. Let's start with acquiring the data and creating a schema and processing pipeline. Regardless of what we ultimately build, we'll want to have an API that returns JSON and CSV. Once we have that, we can really refine the UI. 

We can leave this thread open until then to collect the ideas as this evolves.

**Comment by CarlaAstudillo** [comment]
I'm sure you guys have already seen this on the NICAR list, but NPR recently built a UCR parser for the FBI's clearance data.

Here it is on Github: https://github.com/nprapps/ucr-clearance-parser

Here's the lookup tool that came out of it: http://www.npr.org/2015/03/30/395799413/how-many-crimes-do-your-police-clear-now-you-can-find-out

We can definitely get some good ideas from this.

**Comment by tommeagher** [comment]
Yeah, I saw that on NICAR-L. Very cool. We will definitely want to add some of that from the LEAIC and potentially the clearance data. 
We should also think about finding geographic data for the police jurisdictions in these reports. That may be a heavier lift, for version 2 or 3.
