### ISSUE TITLE
What is "crime index"?

### ISSUE THREAD

**Issue by tommeagher** [HackJersey/crime-scraper#6]
What is crime index and how is that different from total number of crimes? 
The crime index total appears to omit the count of simple assaults. What's happening there?

**Comment by CarlaAstudillo** [comment]
Found the definition in the glossary of terms from the 2012 annual report:
http://www.njsp.org/info/ucr2012/pdf/2012_glossary.pdf
![screen shot 2015-04-08 at 9 11 01 pm](https://cloud.githubusercontent.com/assets/1848921/7058751/f96bd75c-de33-11e4-847d-6361adc3515b.png)

**Comment by tommeagher** [comment]
Thanks for tracking that down, @CarlaAstudillo. Does the FBI use that terminology in the UCR, or is that a Jersey thing?
